---
- hosts: default
  remote_user: vagrant
  become: true
  tasks:

  - name: Add apt repository
    apt_repository:
      repo: 'ppa:webupd8team/java'
      state: present

  - name: Automatically select the Oracle License
    shell: echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections

  - name: Install tools
    apt: name={{ item }} state=latest update_cache=yes
    with_items:
      - git
      - rsync
      - netcat
      - ntp
      - unzip
      - supervisor
      - oracle-java7-installer
      - scala

  - name: Check for spark installation
    stat:
      path: /usr/local/spark
    register: sym

  - name: Download spark
    unarchive:
      src: http://apache.mirrors.tds.net/spark/spark-2.1.0/spark-2.1.0-bin-hadoop2.7.tgz
      dest: /opt
      remote_src: True
      owner: vagrant
      group: vagrant
    when: sym.stat.islnk is not defined

  - name: Install spark
    file:
      src: /opt/spark-2.1.0-bin-hadoop2.7
      dest: /usr/local/spark
      state: link
      owner: vagrant
      group: vagrant
    when: sym.stat.islnk is not defined

  - name: Upload scripts
    copy: src=scripts/ dest=/tmp/ mode=0755

  - name: Configure environment
    shell: /tmp/env_vars
