---

- name: Install scala
  apt: name=scala state=latest
  become: yes

- name: Upload scripts
  copy: src=scripts/ dest=/tmp/ mode=0755

- name: Setup environment variables for spark
  shell: /tmp/env_vars_spark

- name: Check for spark installation
  stat:
    path: /usr/local/spark
  register: sym

- name: Download spark
  unarchive:
    src: "{{ spark_download_url }}"
    dest: /opt
    remote_src: True
    owner: vagrant
    group: vagrant
  when: sym.stat.islnk is not defined
  become: yes

- name: Install spark
  file:
    src: /opt/spark-2.1.0-bin-hadoop2.7
    dest: /usr/local/spark
    state: link
    owner: vagrant
    group: vagrant
  when: sym.stat.islnk is not defined
  become: yes

- name: Copy spark-env config
  copy: src=spark-env.sh dest=/usr/local/spark/conf/spark-env.sh
  become: yes
