---

- name: Copy slaves config
  copy: src=slaves dest=/usr/local/spark/conf/slaves
  become: yes

- name: Start spark master
  shell: exec /usr/local/spark/sbin/start-master.sh

- name: Check if spark is running
  command: systemctl status apache2
  ignore_errors: yes
  changed_when: false
  register: service_apache_status

- name: Report status of Apache
  fail:
    msg: |
      Service apache2 is not running.
      Output of `systemctl status apache2`:
      {{ service_apache_status.stdout }}
      {{ service_apache_status.stderr }}
  when: service_apache_status | failed
